import { db } from './connection';
import { jobs } from './schema';
import { runMigrations } from './migrate';
import { v4 as uuid } from 'uuid';

runMigrations();

const now = new Date();
const daysAgo = (n: number) =>
  new Date(now.getTime() - n * 24 * 60 * 60 * 1000).toISOString();

const seedData = [
  {
    id: uuid(),
    jobTitle: 'Frontend Engineer',
    company: 'Stripe',
    positionType: 'full_time',
    positionLength: null,
    dateAdded: daysAgo(14),
    dateApplied: daysAgo(12),
    applied: true,
    applicationLink: 'https://stripe.com/jobs/frontend-engineer',
    comments: 'Great company culture. Applied through website.',
    externalLinks: '["https://stripe.com/about"]',
    status: 'interview',
    createdAt: daysAgo(14),
    updatedAt: daysAgo(3),
  },
  {
    id: uuid(),
    jobTitle: 'Software Engineering Intern',
    company: 'Google',
    positionType: 'internship',
    positionLength: 3,
    dateAdded: daysAgo(21),
    dateApplied: daysAgo(20),
    applied: true,
    applicationLink: 'https://careers.google.com',
    comments: 'Summer 2026 internship. Applied via referral.',
    externalLinks: '["https://buildyourfuture.withgoogle.com"]',
    status: 'applied',
    createdAt: daysAgo(21),
    updatedAt: daysAgo(20),
  },
  {
    id: uuid(),
    jobTitle: 'Full Stack Developer',
    company: 'Shopify',
    positionType: 'full_time',
    positionLength: null,
    dateAdded: daysAgo(7),
    dateApplied: daysAgo(5),
    applied: true,
    applicationLink: 'https://shopify.com/careers',
    comments: 'Remote position. React + Node stack.',
    externalLinks: '[]',
    status: 'applied',
    createdAt: daysAgo(7),
    updatedAt: daysAgo(5),
  },
  {
    id: uuid(),
    jobTitle: 'Backend Engineer',
    company: 'Netflix',
    positionType: 'full_time',
    positionLength: null,
    dateAdded: daysAgo(30),
    dateApplied: daysAgo(28),
    applied: true,
    applicationLink: 'https://jobs.netflix.com',
    comments: 'Java/Spring position. Got rejection email.',
    externalLinks: '[]',
    status: 'rejected',
    createdAt: daysAgo(30),
    updatedAt: daysAgo(10),
  },
  {
    id: uuid(),
    jobTitle: 'DevOps Co-op',
    company: 'IBM',
    positionType: 'co_op',
    positionLength: 4,
    dateAdded: daysAgo(5),
    dateApplied: null,
    applied: false,
    applicationLink: 'https://ibm.com/employment',
    comments: 'Need to update resume before applying.',
    externalLinks: '[]',
    status: 'not_applied',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: uuid(),
    jobTitle: 'React Developer',
    company: 'Vercel',
    positionType: 'full_time',
    positionLength: null,
    dateAdded: daysAgo(10),
    dateApplied: daysAgo(9),
    applied: true,
    applicationLink: 'https://vercel.com/careers',
    comments: 'Next.js team. Dream company!',
    externalLinks: '["https://vercel.com/blog"]',
    status: 'interview',
    createdAt: daysAgo(10),
    updatedAt: daysAgo(2),
  },
  {
    id: uuid(),
    jobTitle: 'Software Engineer II',
    company: 'Microsoft',
    positionType: 'full_time',
    positionLength: null,
    dateAdded: daysAgo(45),
    dateApplied: daysAgo(44),
    applied: true,
    applicationLink: 'https://careers.microsoft.com',
    comments: 'Azure team. Passed final round!',
    externalLinks: '[]',
    status: 'accepted',
    createdAt: daysAgo(45),
    updatedAt: daysAgo(1),
  },
  {
    id: uuid(),
    jobTitle: 'Data Engineer Intern',
    company: 'Databricks',
    positionType: 'internship',
    positionLength: 3,
    dateAdded: daysAgo(3),
    dateApplied: null,
    applied: false,
    applicationLink: 'https://databricks.com/careers',
    comments: 'Spark/Python role. Interesting team.',
    externalLinks: '[]',
    status: 'not_applied',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: uuid(),
    jobTitle: 'UI/UX Engineer',
    company: 'Figma',
    positionType: 'full_time',
    positionLength: null,
    dateAdded: daysAgo(8),
    dateApplied: daysAgo(7),
    applied: true,
    applicationLink: 'https://figma.com/careers',
    comments: 'Design systems team. Great intersection of design and code.',
    externalLinks: '["https://figma.com/blog/design-systems"]',
    status: 'applied',
    createdAt: daysAgo(8),
    updatedAt: daysAgo(7),
  },
  {
    id: uuid(),
    jobTitle: 'Contract Frontend Developer',
    company: 'Toptal',
    positionType: 'contract',
    positionLength: 6,
    dateAdded: daysAgo(2),
    dateApplied: daysAgo(1),
    applied: true,
    applicationLink: 'https://toptal.com',
    comments: '6-month contract. React + TypeScript.',
    externalLinks: '[]',
    status: 'applied',
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
  {
    id: uuid(),
    jobTitle: 'Platform Engineer',
    company: 'Cloudflare',
    positionType: 'full_time',
    positionLength: null,
    dateAdded: daysAgo(18),
    dateApplied: daysAgo(17),
    applied: true,
    applicationLink: 'https://cloudflare.com/careers',
    comments: 'Workers team. Distributed systems focus.',
    externalLinks: '["https://blog.cloudflare.com"]',
    status: 'rejected',
    createdAt: daysAgo(18),
    updatedAt: daysAgo(8),
  },
  {
    id: uuid(),
    jobTitle: 'Mobile Developer Co-op',
    company: 'Uber',
    positionType: 'co_op',
    positionLength: 8,
    dateAdded: daysAgo(1),
    dateApplied: null,
    applied: false,
    applicationLink: 'https://uber.com/careers',
    comments: 'React Native position. 8-month co-op.',
    externalLinks: '[]',
    status: 'not_applied',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
];

// Clear existing data and seed
db.delete(jobs).run();

for (const job of seedData) {
  db.insert(jobs).values(job as any).run();
}

console.log(`Seeded ${seedData.length} job applications`);
